### PR TITLE
[MM-57738] Retrieve Id through GetPluginID method in Manifest model

### PR DESCRIPTION
**Pull request by willypuzzle**
#### Summary
Changed the way plugin ID is retrieved from the manifest. Instead of directly accessing the Id property, now using the GetPluginID() method for better encapsulation and consistency.

#### Ticket Link
Fixes https://github.com/mattermost/mattermost/issues/26710

#### Related PR
https://github.com/mattermost/mattermost/pull/27281

### CODE REVIEW

**Review by mickmister — COMMENTED** [review]
Hi @willypuzzle, thanks for this contribution! We'll need to wait until https://github.com/mattermost/mattermost/pull/27281 is merged, and then we'll update the imported version in this plugin's `go.mod` file. Just letting you know in case that wasn't known yet :+1: Nice work on this!

**Comment by willypuzzle** [comment]
@mickmister sorry, if I bother you but but due that https://github.com/mattermost/mattermost/pull/27281 was merged shouldn't we make start the Ci/CD again? Or I have to commit something?

**Comment by willypuzzle** [comment]
@mickmister we should merge this PR, it's relative to ne feature for API of the plugin

**Comment by mickmister** [comment]
Hi @willypuzzle, thanks for pinging on this. There is one remaining issue in CI that needs to be addressed here https://github.com/mattermost/mattermost-plugin-starter-template/actions/runs/9380693770/job/25854231700?pr=199 

```
# github.com/mattermost/mattermost-plugin-starter-template/build/manifest
Error: ./main.go:150:2[8](https://github.com/mattermost/mattermost-plugin-starter-template/actions/runs/9380693770/job/25854231700?pr=199#step:4:10):
manifest.GetPluginID undefined (type *model.Manifest has no field or method GetPluginID)
make: build/bin/manifest: No such file or directory
build/setup.mk:21: *** "Cannot parse id from ".  Stop.
Error: Process completed with exit code 2.
```

Specifically this line:

```
manifest.GetPluginID undefined (type *model.Manifest has no field or method GetPluginID)
```

---

In order for the plugin project to use this new method, the server dependency needs to be updated in the plugin project.

It's currently using `v0.0.14`:

https://github.com/mattermost/mattermost-plugin-starter-template/blob/9805832b2f774602bd460d05e6b7d633d00becef/go.mod#L6

The latest is `v0.1.4` https://pkg.go.dev/github.com/mattermost/mattermost/server/public?tab=versions, though it doesn't contain your changes yet. We can reference a commit instead of a tag for our dependency version. 

---

Can you try running this command to update the dependency? This is the merge commit from your PR https://github.com/mattermost/mattermost/commit/4acc4796edb2c1ff93e861b4732c1c758ac76371

```
go get github.com/mattermost/mattermost/server/public@4acc4796edb2c1ff93e861b4732c1c758ac76371
```

Then you can run `make` or individual make commands defined [here](https://developers.mattermost.com/integrate/plugins/developer-workflow) for testing.

**Review by mickmister — APPROVED** [review]

**Review by hanzei — CHANGES_REQUESTED** [review]
Please check out https://github.com/mattermost/mattermost/pull/27281#issuecomment-2191821517

**Pull request closed without merging**
