### PR TITLE
Add separate go.mod to build folder

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

Dependencies have been added to the plugin root directory's `go.mod` in order to support new functionality in the build process. As a result, plugins that sync with the starter template have had their root `go.mod` file altered to support the build functionality.

Having a separate `go.mod` file in the build folder allows us to more easily sync the deps needed to build across repos, as well as keep the build deps separate from the main deps of the plugin.

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-plugin-starter-template/issues/113

### CODE REVIEW

**Comment by mickmister** [comment]
I see the repo sync tool PR already has its dependencies in a separate `go.mod` file now [`0b067fe` (#86)](https://github.com/mattermost/mattermost-plugin-starter-template/pull/86/commits/0b067fee6a2a226158853b81ae7b59dd9e3db264) in the `build/sync` folder. I've excluded the dependencies that are specific to the sync tool in this PR. @hanzei Do you think all build dependencies should go in one `go.mod` file in the `build` directory?

**Comment by hanzei** [comment]
Yes, that makes sense to me. A separate `go.mod` for every directory in `build` seams to much, when we can just keep one.

**Review by jfrerich — APPROVED** [review]
I like this new approach!

**Review by hanzei — APPROVED** [review]
Nice cleanup :+1:

**Comment by hanzei** [comment]
The CI failure will be fixed with https://github.com/mattermost/mattermost-plugin-starter-template/pull/124

**Pull request merged**
